name: Embedded
on:
  workflow_call:
    outputs:
      test1:
        value: ${{ jobs.build.outputs.test1 }}
      test2:
        value: ${{ jobs.build.outputs.test2 }}
      test3:
        value: ${{ jobs.build.outputs.test3 }}
      test4:
        value: ${{ jobs.build.outputs.test4 }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      test1: ${{ steps.setup.outputs.test1 }}
      test2: ${{ steps.setup.outputs.test2 }}
      test3: ${{ steps.setup.outputs.test3 }}
      test4: ${{ steps.setup.outputs.test4 }}
    steps:
      - name: Setup
        id: setup
        run: |
          TEST1=
          echo TEST1=$TEST1
          echo "::set-output name=test1::$TEST1"
          TEST2=true
          echo TEST2=$TEST2
          echo "::set-output name=test2::$TEST2"
          TEST3=false
          echo TEST3=$TEST3
          echo "::set-output name=test3::$TEST3"
          TEST4=0
          echo TEST4=$TEST4
          echo "::set-output name=test4::$TEST4"
         